name: static-check

on:
  workflow_call:

jobs:
  static-checks:
    name: static check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false

      - name: Verify and Install Dependencies
        run: |
          go mod tidy
          go mod download
          go mod verify

      - name: Run Static Analysis
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Run go vet
        run: go vet ./...