name: build

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false

      - name: Verify Dependencies
        run: go mod verify

      - name: Build Project
        run: go build -v -o bin/tracker ./cmd/main.go