name: build

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Load environment from .env file
        run: |
          echo "GO_VERSION=$(grep GO_VERSION ./build/.env | cut -d '=' -f2)" >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Verify Dependencies
        run: go mod verify

      - name: Build Project
        run: go build -v -o bin/tracker ./cmd/main.go

#      - name: Upload built artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: tracker
#          path: bin/tracker

