name: golangci

on:
  workflow_call:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load environment from .env file
        run: |
          echo "GO_VERSION=$(grep GO_VERSION ./build/.env | cut -d '=' -f2)" >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m --config=./.golangci.yml --issues-exit-code=1