name: golangci

on:
  workflow_call:
    inputs:
      GO_VERSION:
        required: true
        type: string

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m --config=./.golangci.yml --issues-exit-code=1