name: Main CI
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true


jobs:
  load-env:
    uses: ./.github/workflows/env.yml

  static-check:
    uses: ./.github/workflows/static-check.yml

  golangci:
    uses: ./.github/workflows/golangci.yml
    needs: [load-env]
    with:
      GO_VERSION: ${{ needs.load-env.outputs.GO_VERSION }}

  build:
    uses: ./.github/workflows/build.yml
    needs: [static-check, golangci, load-env]

  go-test:
    uses: ./.github/workflows/go_test.yml
    needs: [static-check, golangci]
    with:
      MIN_COVERAGE: 50.0

  migration-dry:
    uses: ./.github/workflows/migration_dry.yml
    needs: [static-check, golangci, load-env]
    with:
      DB_USER: ${{ needs.load-env.outputs.DB_USER }}
      DB_PASSWORD: ${{ needs.load-env.outputs.DB_PASSWORD }}
      DB_NAME: ${{ needs.load-env.outputs.DB_NAME }}
      DB_HOST: ${{ needs.load-env.outputs.DB_HOST }}
      DB_PORT: ${{ needs.load-env.outputs.DB_PORT }}
