name: Migration PROD

on:
  workflow_dispatch:

jobs:
  manual-migration:
    name: "migration: prod"
    runs-on: ubuntu-latest
#    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Install Goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          echo "Goose installed successfully"
          echo "$HOME/go/bin" >> $GITHUB_PATH # Add Go binaries to PATH

      - name: Run Up Migrations on Remote Database
        run: |
          if [ -z "${{ secrets.DB_HOST }}" ]; then
             echo "Skipping migration_prod: DB_HOST secret is missing."
             exit 1
           fi
           goose -dir ./migrations/ up
        env:
          GOOSE_DRIVER: "postgres"
          GOOSE_DBSTRING: "postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?sslmode=disable"