name: Publish Docker Image

on:
  workflow_run:
    workflows: ["Main CI"]
    types:
      - completed
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment from .env file
        run: |
          echo "GO_VERSION=$(grep GO_VERSION ./build/.env | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: List downloaded files
        run: ls -l bin

      - name: Debug Info
        run: |
          echo "GO_VERSION: ${{ env.GO_VERSION }}"
          echo "IMAGE_TAG: ${{ github.ref_name }}"

      - name: Build and push Docker image
        run: |
          make container GO_VERSION=${{ env.GO_VERSION }} && \
          IMAGE_TAG=${{ github.ref_name }} && \
          docker tag tracker ${{ secrets.DOCKERHUB_USERNAME }}/tracker:latest && \
          docker tag tracker ${{ secrets.DOCKERHUB_USERNAME }}/tracker:$IMAGE_TAG && \
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tracker:latest && \
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tracker:$IMAGE_TAG
