name: publish docker image

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        type: string


jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment from .env file
        run: |
          echo "GO_VERSION=$(grep GO_VERSION ./build/.env | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Extract version from branch name
        id: extract-version
        run: |
          BRANCH_NAME="${{ inputs.branch }}"
          if [[ "$BRANCH_NAME" =~ ^release/(v[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "Extracted version: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "Branch name does not match the expected format (release/vX.Y.Z)"
            exit 1
          fi

      - name: Create Git tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug Info
        run: |
          echo "GO_VERSION: ${{ env.GO_VERSION }}"

      - name: Build and push Docker image
        run: |
          make container GO_VERSION=${{ env.GO_VERSION }} && \
          docker tag tracker ${{ secrets.DOCKERHUB_USERNAME }}/tracker:latest && \
          docker tag tracker ${{ secrets.DOCKERHUB_USERNAME }}/tracker:$VERSION && \
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tracker:latest && \
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tracker:$VERSION
